version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adt-se-backend
    ports:
      - "8000:8000"
      - "9999:9999"
    env_file:
      - .env
    volumes:
      - ./workspace:/app/workspace
      - ./data:/app/data
    restart: unless-stopped